from django.test import TestCase
from .models import Category, Product

class CategoryTests(TestCase):
    def setUp(self):
        """Create a category"""
        self.category_1 = Category.objects.create(name='foo')

    def test_slug_autogenerated(self):
        """test the slug is generated from the name"""
        self.assertEquals(self.category_1.slug, 'foo')

    def test_slug_change_when_username_changes(self):
        self.category_1.name = 'bar'
        self.category_1.save()

        self.assertNotEquals(self.category_1.slug, 'foo')
        self.assertEquals(self.category_1.slug, 'bar')

    def test_product_creation(self):
        """test the product creation only requires category, name and price"""
        product = Product.objects.create(category=self.category_1, price=20.44, name='sweet rolls')
        
        self.assertIsInstance(product, Product)
        
        # slug is autogenerated
        self.assertEquals(product.slug, 'sweet-rolls')
