# Generated by Django 4.2.5 on 2023-12-06 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address_address_account_add_created_f5b03b_idx'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_to',
            field=models.ForeignKey(limit_choices_to={models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL): models.F('user')}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='account.address'),
        ),
    ]
